### ISSUE TITLE
Unexpected but consistent crashes

### ISSUE THREAD

**Issue by magicalraccoon** [prashantgupta24/automatic-mouse-mover#63]
AMM has been terminating unexpectedly for some time, possibly since updating MacOS. I'm currently running Sonoma 14.6.1

```
INFO[2024-12-09T11:24:05-08:00] Is system sleeping? : false : moved mouse at : 2024-12-09 11:24:05.354298 -0800 PST m=+240.574924709

INFO[2024-12-09T11:25:05-08:00] activity detected in the last 60 seconds.
INFO[2024-12-09T11:25:05-08:00] Activity type:
INFO[2024-12-09T11:25:05-08:00] activityType : cursor-move times: 5
INFO[2024-12-09T11:25:05-08:00] activityType : mouse-click times: 4
INFO[2024-12-09T11:25:05-08:00] activityType : screen-change times: 2
INFO[2024-12-09T11:25:05-08:00]


SIGILL: illegal instruction
PC=0x7ff81695b450 m=11 sigcode=1
instruction bytes: 0xf 0xb 0x48 0x8d 0x5 0x34 0x37 0x19 0x0 0x48 0x89 0x5 0x58 0x47 0x48 0x41

goroutine 0 [idle]:
runtime: unknown pc 0x7ff81695b450
stack: frame={sp:0x2092ce4f8, fp:0x0} stack=[0x209250350,0x2092cff50)
00000002092ce3f8:  0000000000000007  0000000000000339
00000002092ce408:  000060000224d100  0000600002200140
00000002092ce418:  0000000000000339  00000002092ce480
00000002092ce428:  00000002092ce480  0000000004397a38
00000002092ce438:  00006000039647b0  0000600002200140
00000002092ce448:  00000002092ce480  00000002092ce470
00000002092ce458:  00007ff8167900e0  0000000000000000
00000002092ce468:  0000000000000339  00000002092ce4c0
00000002092ce478:  00007ff816723ae8  00007ff81cc0c337
00000002092ce488:  0000000000001068  0000000000000339
00000002092ce498:  00007ff81cc4df3f  a925f7e73f75009f
00000002092ce4a8:  00000002092cfde8  000000000000cea3
00000002092ce4b8:  000000000000d803  00000000000005dc
00000002092ce4c8:  000000000000000f  00000002092cfdc0
00000002092ce4d8:  00007ff81cc26005  0000000000000000
00000002092ce4e8:  00000002092ce590  000000000000000f
00000002092ce4f8: <00007ff8168ce2d0  00000002092ce520
00000002092ce508:  00007ff8167a90de  0000000000000006
00000002092ce518:  00000002092ce5cf  00000002092ce570
00000002092ce528:  00007ff81cc14db7  0000000000000000
00000002092ce538:  00000002092ce5b0  00000002092ce5c8
00000002092ce548:  00000002092cfe38  00000000043979d8
00000002092ce558:  000000c00008e5c8  00000002092ce5cf
00000002092ce568:  0000000000000006  00000002092cfe10
00000002092ce578:  00007ff81cc25d29  0000000000000000
00000002092ce588:  ffff9d8400000339  006f004600580041
00000002092ce598:  0065007300750063  006e006900570064
00000002092ce5a8:  00000077006f0064  636f636f000005dc
00000002092ce5b8:  0000000000000008  0000000000000000
00000002092ce5c8:  0000000000000008  0000000000000000
00000002092ce5d8:  0000000000000323  006f005200580041
00000002092ce5e8:  00007ff80065006c  00007ff83631c5af
runtime: unknown pc 0x7ff81695b450
stack: frame={sp:0x2092ce4f8, fp:0x0} stack=[0x209250350,0x2092cff50)
00000002092ce3f8:  0000000000000007  0000000000000339
00000002092ce408:  000060000224d100  0000600002200140
00000002092ce418:  0000000000000339  00000002092ce480
00000002092ce428:  00000002092ce480  0000000004397a38
00000002092ce438:  00006000039647b0  0000600002200140
00000002092ce448:  00000002092ce480  00000002092ce470
00000002092ce458:  00007ff8167900e0  0000000000000000
00000002092ce468:  0000000000000339  00000002092ce4c0
00000002092ce478:  00007ff816723ae8  00007ff81cc0c337
00000002092ce488:  0000000000001068  0000000000000339
00000002092ce498:  00007ff81cc4df3f  a925f7e73f75009f
00000002092ce4a8:  00000002092cfde8  000000000000cea3
00000002092ce4b8:  000000000000d803  00000000000005dc
00000002092ce4c8:  000000000000000f  00000002092cfdc0
00000002092ce4d8:  00007ff81cc26005  0000000000000000
00000002092ce4e8:  00000002092ce590  000000000000000f
00000002092ce4f8: <00007ff8168ce2d0  00000002092ce520
00000002092ce508:  00007ff8167a90de  0000000000000006
00000002092ce518:  00000002092ce5cf  00000002092ce570
00000002092ce528:  00007ff81cc14db7  0000000000000000
00000002092ce538:  00000002092ce5b0  00000002092ce5c8
00000002092ce548:  00000002092cfe38  00000000043979d8
00000002092ce558:  000000c00008e5c8  00000002092ce5cf
00000002092ce568:  0000000000000006  00000002092cfe10
00000002092ce578:  00007ff81cc25d29  0000000000000000
00000002092ce588:  ffff9d8400000339  006f004600580041
00000002092ce598:  0065007300750063  006e006900570064
00000002092ce5a8:  00000077006f0064  636f636f000005dc
00000002092ce5b8:  0000000000000008  0000000000000000
00000002092ce5c8:  0000000000000008  0000000000000000
00000002092ce5d8:  0000000000000323  006f005200580041
00000002092ce5e8:  00007ff80065006c  00007ff83631c5af

goroutine 73 [syscall]:
runtime.cgocall(0x41ceec0, 0xc00008e5c8, 0xc00008e620)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00008e598 sp=0xc00008e560 pc=0x400655b
github.com/go-vgo/robotgo._Cfunc_get_main_title(0x0)
	_cgo_gotypes.go:593 +0x45 fp=0xc00008e5c8 sp=0xc00008e598 pc=0x41685c5
github.com/go-vgo/robotgo.GetTitle(0x0, 0x0, 0x0, 0xa, 0xc00008e738)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/go-vgo/robotgo@v0.0.0-20190409154511-f2a0505446b2/robotgo.go:1565 +0xd0 fp=0xc00008e610 sp=0xc00008e5c8 pc=0x4168eb0
github.com/prashantgupta24/activity-tracker/internal/pkg/handler.checkScreenChange(0xc0001b09a0, 0xc000122120, 0xc000126010, 0xf)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/screenChangeHandler.go:92 +0x47 fp=0xc00008e7c0 sp=0xc00008e610 pc=0x41c2ea7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00008e7c8 sp=0xc00008e7c0 pc=0x406d761
created by github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*ScreenChangeHandlerStruct).Start.func1
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/screenChangeHandler.go:42 +0x13b

goroutine 1 [syscall, locked to thread]:
github.com/getlantern/systray._Cfunc_nativeLoop(0x0)
	_cgo_gotypes.go:106 +0x45
github.com/getlantern/systray.nativeLoop(...)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190131073753-26d5b920200d/systray_nonwindows.go:19
github.com/getlantern/systray.Run(0x426c840, 0x426c830)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20190131073753-26d5b920200d/systray.go:81 +0x7f
main.main()
	/Users/prashantgupta@us.ibm.com/Documents/IBM/external/automatic-mouse-mover/cmd/main.go:13 +0x39

goroutine 19 [syscall]:
github.com/prashantgupta24/mac-sleep-notifier/notifier._Cfunc_registerNotifications()
	_cgo_gotypes.go:44 +0x3c
github.com/prashantgupta24/mac-sleep-notifier/notifier.StartNotifier()
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/mac-sleep-notifier@v0.1.1/notifier/notifierMain.go:12 +0x25
github.com/prashantgupta24/mac-sleep-notifier/notifier.(*Notifier).Start.func1()
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/mac-sleep-notifier@v0.1.1/notifier/notifier.go:20 +0x25
created by github.com/prashantgupta24/mac-sleep-notifier/notifier.(*Notifier).Start
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/mac-sleep-notifier@v0.1.1/notifier/notifier.go:20 +0x9c

goroutine 18 [select]:
main.onReady.func1()
	/Users/prashantgupta@us.ibm.com/Documents/IBM/external/automatic-mouse-mover/cmd/main.go:33 +0x25c
created by main.onReady
	/Users/prashantgupta@us.ibm.com/Documents/IBM/external/automatic-mouse-mover/cmd/main.go:17 +0x35

goroutine 7 [chan receive]:
github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*MouseClickHandlerStruct).Start.func1(0xc000012ed0, 0xc0000765a0, 0xc000024420)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/mouseClickHandler.go:32 +0x85
created by github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*MouseClickHandlerStruct).Start
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/mouseClickHandler.go:30 +0x199

goroutine 8 [chan receive]:
github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*MouseCursorHandlerStruct).Start.func1(0xc000012ee0, 0xc0000765a0)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/mouseCursorHandler.go:38 +0x68
created by github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*MouseCursorHandlerStruct).Start
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/mouseCursorHandler.go:36 +0x168

goroutine 9 [select]:
github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*ScreenChangeHandlerStruct).Start.func1(0xc000012ef0, 0xc0000765a0)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/screenChangeHandler.go:43 +0x1bc
created by github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*ScreenChangeHandlerStruct).Start
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/screenChangeHandler.go:36 +0x168

goroutine 10 [select]:
github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*MachineSleepHanderStruct).Start.func1(0xc000012f00, 0xc0000765a0, 0xc0001b07e0)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/machineSleepHandler.go:31 +0xd1
created by github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*MachineSleepHanderStruct).Start
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/machineSleepHandler.go:28 +0x175

goroutine 11 [select]:
github.com/prashantgupta24/activity-tracker/pkg/tracker.(*Instance).StartWithHandlers.func1(0xc0000100a8, 0xc0001b07e0, 0xc0001b0770)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/pkg/tracker/tracker.go:55 +0x245
created by github.com/prashantgupta24/activity-tracker/pkg/tracker.(*Instance).StartWithHandlers
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/pkg/tracker/tracker.go:41 +0x2b1

goroutine 12 [select]:
github.com/prashantgupta24/automatic-mouse-mover/pkg/mousemover.(*MouseMover).run.func1(0xc00000e1f8, 0xc000076600, 0xc0001b0770)
	/Users/prashantgupta@us.ibm.com/Documents/IBM/external/automatic-mouse-mover/pkg/mousemover/mouseMover.go:52 +0x399
created by github.com/prashantgupta24/automatic-mouse-mover/pkg/mousemover.(*MouseMover).run
	/Users/prashantgupta@us.ibm.com/Documents/IBM/external/automatic-mouse-mover/pkg/mousemover/mouseMover.go:42 +0x53

goroutine 20 [chan receive]:
github.com/prashantgupta24/mac-sleep-notifier/notifier.(*Notifier).Start.func2(0xc000206000)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/mac-sleep-notifier@v0.1.1/notifier/notifier.go:25 +0x37
created by github.com/prashantgupta24/mac-sleep-notifier/notifier.(*Notifier).Start
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/mac-sleep-notifier@v0.1.1/notifier/notifier.go:22 +0xbe

goroutine 149 [syscall]:
github.com/robotn/gohook._Cfunc_add_event(0x600003558250, 0xc000000000)
	_cgo_gotypes.go:67 +0x45
github.com/robotn/gohook.AddEvent(0x4257e24, 0x5, 0x0)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/robotn/gohook@v0.0.0-20190318172628-a7a38946710e/hook.go:190 +0x85
github.com/go-vgo/robotgo.AddEvent(0x4257e24, 0x5, 0x4262a94)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/go-vgo/robotgo@v0.0.0-20190409154511-f2a0505446b2/robotgo.go:1276 +0x19a
github.com/prashantgupta24/activity-tracker/internal/pkg/handler.addMouseClickRegistration(0xc0001b08c0, 0xc0000765a0, 0xc000024420)
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/mouseClickHandler.go:86 +0x76
created by github.com/prashantgupta24/activity-tracker/internal/pkg/handler.(*MouseClickHandlerStruct).Start.func1
	/Users/prashantgupta@us.ibm.com/go/pkg/mod/github.com/prashantgupta24/activity-tracker@v1.0.0/internal/pkg/handler/mouseClickHandler.go:38 +0x190

rax    0x7ff816aeeaae
rbx    0xc00008e5c8
rcx    0x0
rdx    0x2092ce5a8
rdi    0xe6
rsi    0xc00008e5c8
rbp    0x2092ce500
rsp    0x2092ce4f8
r8     0x2092ce5b0
r9     0x0
r10    0x92
r11    0x9c
r12    0xffffffff
r13    0x2092ce5a8
r14    0xc00008e5c8
r15    0x0
rip    0x7ff81695b450
rflags 0x203
cs     0x2b
fs     0x0
gs     0x0
```

**Comment by Resousse** [comment]
Hello @magicalraccoon, I'm very late, but this week the application creator offered me the opportunity to continue the improvement of this application.

I think this release will fix this issue, let me know : https://github.com/Resousse/automatic-mouse-mover/releases/tag/v1.0.5
If everything is ok, do not forget to close this issue, as I don't have right to close it.
